version: '3.9'

services:
  sql-server-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-server-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=lima@001
    ports:
      - "1433:1433"
    networks:
      - lima

networks:
  lima:
    driver: bridge